#pragma once
#include <stdbool.h>

#define stream_ame_comic 0
#define stream_ame_drag 1
#define stream_ame_egosearching 2
#define stream_ame_egosearching_ura 3
#define stream_ame_hair_drill 4
#define stream_ame_hair_long 5
#define stream_ame_hair_poney 6
#define stream_ame_hair_side 7
#define stream_ame_handspinner1 8
#define stream_ame_handspinner2 9
#define stream_ame_headphone 10
#define stream_ame_henoji 11
#define stream_ame_henoji_dark 12
#define stream_ame_idle 13
#define stream_ame_movie 14
#define stream_ame_nail 15
#define stream_ame_selfie 16
#define stream_ame_sex 17
#define stream_ame_sleep 18
#define stream_ame_smile 19
#define stream_ame_tv 20
#define stream_ame_voice_training 21
#define stream_ame_yanda_carisma 22
#define stream_ame_yanderu 23
#define stream_ame_yanderu_random 24
#define stream_cho_akaruku 25
#define stream_cho_akaruku_fever 26
#define stream_cho_akaruku_superchat 27
#define stream_cho_akaruku_win_stop 28
#define stream_cho_chance_blackout 29
#define stream_cho_chance_blackout_back 30
#define stream_cho_chance_porori_idle 31
#define stream_cho_chance_porori_win 32
#define stream_cho_chance_porori_win2 33
#define stream_cho_chance_porori_win3 34
#define stream_cho_chance_porori_win_stop 35
#define stream_cho_dokuzetsu 36
#define stream_cho_dokuzetsu_fever 37
#define stream_cho_dokuzetsu_superchat 38
#define stream_cho_dokuzetsu_win_stop 39
#define stream_cho_end 40
#define stream_cho_fanservice 41
#define stream_cho_game 42
#define stream_cho_game_fever 43
#define stream_cho_game_superchat 44
#define stream_cho_game_win_stop 45
#define Stream_cho_h 46
#define stream_cho_hera 47
#define stream_cho_hera_fever 48
#define stream_cho_hera_superchat 49
#define stream_cho_hera_win_stop 50
#define stream_cho_h_fever 51
#define stream_cho_h_superchat 52
#define stream_cho_h_win_stop 53
#define stream_cho_kakkoyoku 54
#define stream_cho_kakkoyoku_fever 55
#define stream_cho_kakkoyoku_superchat 56
#define stream_cho_kakkoyoku_win_stop 57
#define stream_cho_kawaiku 58
#define stream_cho_kawaiku_fever 59
#define stream_cho_kawaiku_superchat 60
#define stream_cho_kawaiku_win_stop 61
#define stream_cho_kobiru 62
#define stream_cho_kobiru_fever 63
#define stream_cho_kobiru_superchat 64
#define stream_cho_kobiru_win_stop 65
#define stream_cho_meta 66
#define stream_cho_ntr 67
#define stream_cho_otaku 68
#define stream_cho_otaku2 69
#define stream_cho_otaku_fever 70
#define stream_cho_otaku_superchat 71
#define stream_cho_otaku_win_stop 72
#define stream_cho_porori_pokan 73
#define stream_cho_sayonara 74
#define stream_cho_sayonaraend 75
#define stream_cho_su 76
#define stream_cho_su_fever 77
#define stream_cho_su_smile 78
#define stream_cho_su_superchat 79
#define stream_cho_su_win_stop 80
#define stream_cho_100k_silver 81
#define stream_cho_teitter_inbouron 82
#define stream_cho_teitter_inbouron2 83
#define stream_cho_teitter_inbouron3 84
#define stream_cho_teitter_zatsudan 85
#define stream_cho_slide1 86
#define stream_cho_slide2 87
#define stream_cho_slide_record 88
#define stream_cho_tweet1 89
#define stream_cho_tweet2 90
#define stream_ame_drag_a 91
#define stream_ame_game_a 92
#define stream_ame_idle_anxiety_a 93
#define stream_ame_idle_happy_a 94
#define stream_ame_idle_iraira_a 95
#define stream_ame_idle_normal_a 96
#define stream_ame_movie_a 97
#define stream_ame_negative_a 98
#define stream_ame_out_a 99
#define stream_ame_positive_a 100
#define stream_ame_talk_a 101
#define stream_ame_drag_b 102
#define stream_ame_game_b 103
#define stream_ame_idle_anxiety_b 104
#define stream_ame_idle_happy_b 105
#define stream_ame_idle_iraira_b 106
#define stream_ame_idle_normal_b 107
#define stream_ame_movie_b 108
#define stream_ame_negative_b 109
#define stream_ame_out_b 110
#define stream_ame_positive_b 111
#define stream_ame_talk_b 112
#define stream_ame_drag_c 113
#define stream_ame_game_c 114
#define stream_ame_idle_anxiety_c 115
#define stream_ame_idle_happy_c 116
#define stream_ame_idle_iraira_c 117
#define stream_ame_idle_normal_c 118
#define stream_ame_movie_c 119
#define stream_ame_negative_c 120
#define stream_ame_out_c 121
#define stream_ame_positive_c 122
#define stream_ame_talk_c 123
#define stream_ame_drag_d 124
#define stream_ame_game_d 125
#define stream_ame_idle_anxiety_d 126
#define stream_ame_idle_happy_d 127
#define stream_ame_idle_iraira_d 128
#define stream_ame_idle_normal_d 129
#define stream_ame_movie_d 130
#define stream_ame_negative_d 131
#define stream_ame_out_d 132
#define stream_ame_positive_d 133
#define stream_ame_talk_d 134
#define stream_ame_drag_e 135
#define stream_ame_game_e 136
#define stream_ame_idle_anxiety_e 137
#define stream_ame_idle_happy_e 138
#define stream_ame_idle_iraira_e 139
#define stream_ame_idle_normal_e 140
#define stream_ame_movie_e 141
#define stream_ame_negative_e 142
#define stream_ame_out_e 143
#define stream_ame_positive_e 144
#define stream_ame_talk_e 145
#define stream_ame_drag_f 146
#define stream_ame_game_f 147
#define stream_ame_idle_anxiety_f 148
#define stream_ame_idle_happy_f 149
#define stream_ame_idle_iraira_f 150
#define stream_ame_idle_normal_f 151
#define stream_ame_movie_f 152
#define stream_ame_negative_f 153
#define stream_ame_out_f 154
#define stream_ame_positive_f 155
#define stream_ame_talk_f 156
#define stream_ame_drag_g 157
#define stream_ame_game_g 158
#define stream_ame_idle_anxiety_g 159
#define stream_ame_idle_happy_g 160
#define stream_ame_idle_iraira_g 161
#define stream_ame_idle_normal_g 162
#define stream_ame_movie_g 163
#define stream_ame_negative_g 164
#define stream_ame_out_g 165
#define stream_ame_positive_g 166
#define stream_ame_talk_g 167
#define stream_ame_craziness 168
#define stream_ame_h_heart 169
#define stream_ame_vomiting1 170
#define stream_ame_vomiting2 171
#define stream_cho_angel 172
#define stream_cho_anguri 173
#define stream_cho_anken_business1 174
#define stream_cho_anken_business10 175
#define stream_cho_anken_business2 176
#define stream_cho_anken_business3 177
#define stream_cho_anken_business4 178
#define stream_cho_anken_business5 179
#define stream_cho_anken_business6 180
#define stream_cho_anken_business7 181
#define stream_cho_anken_business8 182
#define stream_cho_anken_business9 183
#define stream_cho_anken_figure1 184
#define stream_cho_anken_figure2 185
#define stream_cho_anken_figure3 186
#define stream_cho_anken_figure4 187
#define stream_cho_anken_figure5 188
#define stream_cho_anken_figure6 189
#define stream_cho_anken_figure7 190
#define stream_cho_anken_game1 191
#define stream_cho_anken_game2 192
#define stream_cho_anken_game3 193
#define stream_cho_anken_game4 194
#define stream_cho_anken_game5 195
#define stream_cho_anken_game6 196
#define stream_cho_anken_game7 197
#define stream_cho_anken_game8 198
#define stream_cho_anken_game9 199
#define stream_cho_anken_juice1 200
#define stream_cho_anken_juice2 201
#define stream_cho_anken_juice3 202
#define stream_cho_anken_juice4 203
#define stream_cho_anken_juice5 204
#define stream_cho_anken_juice6 205
#define stream_cho_anken_juice7 206
#define stream_cho_anken_juice8 207
#define stream_cho_anken_make1 208
#define stream_cho_anken_make2 209
#define stream_cho_anken_make3 210
#define stream_cho_anken_make4 211
#define stream_cho_anken_make5 212
#define stream_cho_anken_make6 213
#define stream_cho_anken_make7 214
#define stream_cho_anken_make8 215
#define stream_cho_anken_make9 216
#define stream_cho_asmr2 217
#define stream_cho_asmr3 218
#define stream_cho_asmr4 219
#define stream_cho_asmr5 220
#define stream_cho_asmr6 221
#define stream_cho_asmr7 222
#define stream_cho_asmr7_end 223
#define stream_cho_asmr8 224
#define stream_cho_bad 225
#define stream_cho_balanceball 226
#define stream_cho_balanceball_smile 227
#define stream_cho_balanceball_start 228
#define stream_cho_balanceball_asmr 229
#define stream_cho_craziness1 230
#define stream_cho_craziness2 231
#define stream_cho_craziness3 232
#define stream_cho_craziness4 233
#define stream_cho_crying_angry 234
#define stream_cho_eeto 235
#define stream_cho_fan1 236
#define stream_cho_fan2 237
#define stream_cho_fan3 238
#define stream_cho_fan4 239
#define stream_cho_fan5 240
#define stream_cho_fan6 241
#define stream_cho_game_ape1 242
#define stream_cho_game_ape2 243
#define stream_cho_game_ape3 244
#define stream_cho_game_ape4 245
#define stream_cho_game_ape5 246
#define stream_cho_game_sayo1 247
#define stream_cho_game_sayo2 248
#define stream_cho_game_sayo3 249
#define stream_cho_game_sayo4 250
#define stream_cho_game_sayo5 251
#define stream_cho_game_twilight1 252
#define stream_cho_game_twilight2 253
#define stream_cho_game_twilight3 254
#define stream_cho_game_twilight4 255
#define stream_cho_game_twilight5 256
#define stream_cho_game_twilight6 257
#define stream_cho_game_twilight7 258
#define stream_cho_game_twilight8 259
#define stream_cho_gaoo 260
#define stream_cho_grandend1 261
#define stream_cho_grandend2 262
#define stream_cho_grandend3 263
#define stream_cho_grandend_bg 264
#define stream_cho_grgr 265
#define stream_cho_grgr2 266
#define stream_cho_grgr3 267
#define stream_cho_grgr4 268
#define stream_cho_g_express1 269
#define stream_cho_g_express1_2 270
#define stream_cho_g_express2 271
#define stream_cho_g_express2_3 272
#define stream_cho_g_express3 273
#define stream_cho_g_express3_4 274
#define stream_cho_g_express4 275
#define stream_cho_hera2 276
#define stream_cho_hera3 277
#define stream_cho_hitotabi1 278
#define stream_cho_hitotabi2 279
#define stream_cho_horror_anger 280
#define stream_cho_horror_bokoboko 281
#define stream_cho_horror_comment 282
#define stream_cho_horror_eeto 283
#define stream_cho_horror_glare 284
#define stream_cho_horror_idle 285
#define stream_cho_horror_iei 286
#define stream_cho_horror_kashikoma 287
#define stream_cho_horror_laugh 288
#define stream_cho_horror_lower 289
#define stream_cho_horror_omae 290
#define stream_cho_horror_smile 291
#define stream_cho_horror_teach 292
#define stream_cho_ice1 293
#define stream_cho_ice2 294
#define stream_cho_ide_end_fin 295
#define stream_cho_ide_end_idle 296
#define stream_cho_ide_invoke 297
#define stream_cho_kashikoma 298
#define stream_cho_kashikoma_otaku 299
#define stream_cho_kobiru_microphone 300
#define stream_cho_kobiru_superchat_microphone 301
#define stream_cho_kyouso1 302
#define stream_cho_kyouso2 303
#define stream_cho_kyouso3 304
#define stream_cho_kyouso4 305
#define stream_cho_kyouso5 306
#define stream_cho_ntr1 307
#define stream_cho_ntr2 308
#define stream_cho_ntr3 309
#define stream_cho_ntr4 310
#define stream_cho_ntr5 311
#define stream_cho_nyo 312
#define stream_cho_peace 313
#define stream_cho_pointing 314
#define stream_cho_pointing2 315
#define stream_cho_pointing_microphone 316
#define stream_cho_pointing_otaku 317
#define stream_cho_pointing_porori 318
#define stream_cho_pout 319
#define stream_cho_pray 320
#define stream_cho_reaction1 321
#define stream_cho_reaction2 322
#define stream_cho_reaction_ape 323
#define stream_cho_reaction_asmr1 324
#define stream_cho_reaction_asmr2 325
#define stream_cho_reaction_game 326
#define stream_cho_reaction_grgr 327
#define stream_cho_reaction_juice 328
#define stream_cho_reaction_make 329
#define stream_cho_reaction_otaku 330
#define stream_cho_reaction_porori 331
#define stream_cho_reaction_twilight 332
#define stream_cho_reaction_yukkuri1 333
#define stream_cho_richter 334
#define stream_cho_sayonara1 335
#define stream_cho_sayonara2 336
#define stream_cho_sayonara3 337
#define stream_cho_shobon 338
#define stream_cho_shobon_smile 339
#define stream_cho_asmr1 340
#define stream_cho_sleepy1 341
#define stream_cho_sleepy2 342
#define stream_cho_sleepy3 343
#define stream_cho_sorrow_smile 344
#define stream_cho_teach 345
#define stream_cho_teach2 346
#define stream_cho_teach3 347
#define stream_cho_unrest 348
#define stream_cho_vomiting1 349
#define stream_cho_vomiting2 350
#define stream_cho_yukkuri_anger 351
#define stream_cho_yukkuri_bye 352
#define stream_cho_yukkuri_cry 353
#define stream_cho_yukkuri_idle 354
#define stream_cho_yukkuri_smile 355
#define stream_cho_yukkuri_teach 356
#define stream_cho_yukkuri_wink 357
#define stream_cho_b_angle 358
#define stream_cho_b_craziness1 359
#define stream_cho_b_craziness2 360
#define stream_cho_b_idle 361
#define stream_cho_b_idle2_1 362
#define stream_cho_b_idle2_2 363
#define stream_cho_b_lower1 364
#define stream_cho_b_lower2 365
#define stream_cho_b_neckcut 366
#define stream_cho_b_wristcut1_1 367
#define stream_cho_b_wristcut1_2 368
#define stream_cho_b_wristcut1_3 369
#define ANIMATION_FINISHED 370

typedef int animation_t;

extern const int frame_counts[];
extern const bool loop_list[];
extern const double durations[][132];
extern const char* frames_list[][132];
